nodeLinker: node-modules

npmScopes:
  ramm:
    # This is the syntax to be used when pulling multiple packages from a GitLab group's private
    # registry.
    #npmRegistryServer: "https://gitlab.com/api/v4/groups/65423230/-/packages/npm"
    npmRegistryServer: 'https://gitlab.com/api/v4/projects/54281288/packages/npm/'
    npmAlwaysAuth: true
    npmAuthToken: "${RAMM_SUI_SDK_GITLAB_AUTH_TOKEN}"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
